### ISSUE TITLE
Include images for auth services

### ISSUE THREAD

**Issue by kanarinka** [mitmedialab/Terra-Incognita#111]
Could you include images/colors for Twitter/Facebook/Google logins so they will look familiar to people immediately? Something like this for each service:

![image](https://cloud.githubusercontent.com/assets/1102550/23255522/f03f9218-f989-11e6-965b-ec3728577d76.png)

**Comment by s2tephen** [comment]
Just used Font Awesome + https://lipis.github.io/bootstrap-social/ as a quick out-of-the-box solution, but may be overkill to load in an entire icon font for just three images. Also Google has updated their branding guidelines (https://developers.google.com/identity/branding-guidelines) so that particular button styling is out of date, if that matters.

![image](https://cloud.githubusercontent.com/assets/1381021/23257238/f8830700-f990-11e6-8af1-b9dc2f1dd616.png)
